export const tasks_seed: Task[] = [
   { id: "1", pinned: false, deet: "Design UI templates for next project", status: "in-progress" as Status, createdAt: new Date(), due: new Date(), priority: "high" as Priority},
   { id: "1", pinned: false, deet: "Write article on alpinejs and dexie", status: "in-progress" as Status, createdAt: new Date(), due: new Date(), priority: "low" as Priority},
   { id: "1", pinned: false, deet: "Finish chrome extension", status: "completed" as Status, createdAt: new Date(), due: new Date(), priority: "high" as Priority},
   { id: "1", pinned: false, deet: "Create UI design for vendor pages", status: "unfulfilled" as Status, createdAt: new Date(), due: new Date(), priority: "medium" as Priority},
   { id: "1", pinned: false, deet: "Complete alorithms course", status: "completed" as Status, createdAt: new Date(), due: new Date(), priority: "medium" as Priority},
   { id: "1", pinned: false, deet: "Complete alorithms course", status: "in-progress" as Status, createdAt: new Date(), due: new Date(), priority: "high" as Priority},
   { id: "1", pinned: false, deet: "Complete alorithms course", status: "completed" as Status, createdAt: new Date(), due: new Date(), priority: "medium" as Priority},
   { id: "1", pinned: false, deet: "Complete alorithms course", status: "unfulfilled" as Status, createdAt: new Date(), due: new Date(), priority: "low" as Priority},
   { id: "1", pinned: false, deet: "Complete alorithms course", status: "unfulfilled" as Status, createdAt: new Date(), due: new Date(), priority: "high" as Priority},
   { id: "1", pinned: false, deet: "Complete alorithms course", status: "unfulfilled" as Status, createdAt: new Date(), due: new Date(), priority: "medium" as Priority},
   { id: "1", pinned: false, deet: "Complete alorithms course", status: "unfulfilled" as Status, createdAt: new Date(), due: new Date(), priority: "low" as Priority},
   { id: "1", pinned: false, deet: "Complete alorithms course", status: "unfulfilled" as Status, createdAt: new Date(), due: new Date(), priority: "medium" as Priority},
   { id: "1", pinned: false, deet: "Complete alorithms course", status: "unfulfilled" as Status, createdAt: new Date(), due: new Date(), priority: "medium" as Priority},
   { id: "1", pinned: false, deet: "Complete alorithms course", status: "in-progress" as Status, createdAt: new Date(), due: new Date(), priority: "low" as Priority},
]