export const tasks_seed: Task[] = [
   { id: 1, deet: "Design UI templates for next project", status: "in-progress", createdAt: new Date(), due: new Date(), priority: 1},
   { id: 1, deet: "Write article on alpinejs and dexie", status: "in-progress", createdAt: new Date(), due: new Date(), priority: 1},
   { id: 1, deet: "Finish chrome extension", status: "completed", createdAt: new Date(), due: new Date(), priority: 1},
   { id: 1, deet: "Create UI design for vendor pages", status: "unfulfilled", createdAt: new Date(), due: new Date(), priority: 1},
   { id: 1, deet: "Complete alorithms course", status: "completed", createdAt: new Date(), due: new Date(), priority: 1},
   { id: 1, deet: "Complete alorithms course", status: "in-progress", createdAt: new Date(), due: new Date(), priority: 1},
   { id: 1, deet: "Complete alorithms course", status: "completed", createdAt: new Date(), due: new Date(), priority: 1},
   { id: 1, deet: "Complete alorithms course", status: "unfulfilled", createdAt: new Date(), due: new Date(), priority: 1},
   { id: 1, deet: "Complete alorithms course", status: "unfulfilled", createdAt: new Date(), due: new Date(), priority: 1},
   { id: 1, deet: "Complete alorithms course", status: "unfulfilled", createdAt: new Date(), due: new Date(), priority: 1},
   { id: 1, deet: "Complete alorithms course", status: "unfulfilled", createdAt: new Date(), due: new Date(), priority: 1},
   { id: 1, deet: "Complete alorithms course", status: "unfulfilled", createdAt: new Date(), due: new Date(), priority: 1},
   { id: 1, deet: "Complete alorithms course", status: "unfulfilled", createdAt: new Date(), due: new Date(), priority: 1},
   { id: 1, deet: "Complete alorithms course", status: "in-progress", createdAt: new Date(), due: new Date(), priority: 1},
]